// Code generated by protoc-gen-go. DO NOT EDIT.
// source: osprey.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	osprey.proto

It has these top-level messages:
	LoginRequest
	ConsumeLoginResponse
	Cluster
	AuthProvider
	User
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginRequest struct {
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type LoginResponse struct {
	Cluster  *Cluster      `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	Provider *AuthProvider `protobuf:"bytes,2,opt,name=provider" json:"provider,omitempty"`
	User     *User         `protobuf:"bytes,3,opt,name=user" json:"user,omitempty"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginResponse) GetCluster() *Cluster {
	if m != nil {
		return m.Cluster
	}
	return nil
}

func (m *LoginResponse) GetProvider() *AuthProvider {
	if m != nil {
		return m.Provider
	}
	return nil
}

func (m *LoginResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type Cluster struct {
	Name         string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ApiServerURL string `protobuf:"bytes,2,opt,name=apiServerURL" json:"apiServerURL,omitempty"`
	ApiServerCA  string `protobuf:"bytes,3,opt,name=apiServerCA" json:"apiServerCA,omitempty"`
}

func (m *Cluster) Reset()                    { *m = Cluster{} }
func (m *Cluster) String() string            { return proto.CompactTextString(m) }
func (*Cluster) ProtoMessage()               {}
func (*Cluster) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Cluster) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Cluster) GetApiServerURL() string {
	if m != nil {
		return m.ApiServerURL
	}
	return ""
}

func (m *Cluster) GetApiServerCA() string {
	if m != nil {
		return m.ApiServerCA
	}
	return ""
}

type AuthProvider struct {
	ClientID     string `protobuf:"bytes,1,opt,name=clientID" json:"clientID,omitempty"`
	ClientSecret string `protobuf:"bytes,2,opt,name=clientSecret" json:"clientSecret,omitempty"`
	IssuerURL    string `protobuf:"bytes,3,opt,name=issuerURL" json:"issuerURL,omitempty"`
	IssuerCA     string `protobuf:"bytes,4,opt,name=issuerCA" json:"issuerCA,omitempty"`
}

func (m *AuthProvider) Reset()                    { *m = AuthProvider{} }
func (m *AuthProvider) String() string            { return proto.CompactTextString(m) }
func (*AuthProvider) ProtoMessage()               {}
func (*AuthProvider) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AuthProvider) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *AuthProvider) GetClientSecret() string {
	if m != nil {
		return m.ClientSecret
	}
	return ""
}

func (m *AuthProvider) GetIssuerURL() string {
	if m != nil {
		return m.IssuerURL
	}
	return ""
}

func (m *AuthProvider) GetIssuerCA() string {
	if m != nil {
		return m.IssuerCA
	}
	return ""
}

type User struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Token    string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "pb.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "pb.ConsumeLoginResponse")
	proto.RegisterType((*Cluster)(nil), "pb.Cluster")
	proto.RegisterType((*AuthProvider)(nil), "pb.AuthProvider")
	proto.RegisterType((*User)(nil), "pb.User")
}

func init() { proto.RegisterFile("osprey.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x91, 0x3f, 0x4b, 0xf4, 0x40,
	0x10, 0xc6, 0xc9, 0xbd, 0x79, 0xbd, 0x64, 0x12, 0x45, 0x06, 0x8b, 0x20, 0x57, 0x1c, 0x0b, 0x82,
	0x85, 0xa4, 0xd0, 0xc6, 0x36, 0xc4, 0x46, 0xb8, 0x42, 0xf6, 0xb8, 0x0f, 0x70, 0x89, 0x83, 0x06,
	0xcf, 0xec, 0xba, 0xbb, 0x39, 0xb0, 0xb5, 0xf2, 0x63, 0xcb, 0xfe, 0x49, 0x8c, 0xdd, 0x3e, 0xbf,
	0x3c, 0xcc, 0x6f, 0x86, 0x40, 0x2e, 0xb4, 0x54, 0xf4, 0x59, 0x4a, 0x25, 0x8c, 0xc0, 0x85, 0x6c,
	0xd8, 0x19, 0xe4, 0x1b, 0xf1, 0xd2, 0xf5, 0x9c, 0x3e, 0x06, 0xd2, 0x86, 0x7d, 0x45, 0x70, 0x1a,
	0x80, 0x96, 0xa2, 0xd7, 0x84, 0x57, 0xb0, 0x6c, 0x0f, 0x83, 0x36, 0xa4, 0x8a, 0x68, 0x1d, 0x5d,
	0x67, 0xb7, 0x59, 0x29, 0x9b, 0xb2, 0xf6, 0x88, 0x8f, 0xdf, 0xf0, 0x06, 0x12, 0xa9, 0xc4, 0xb1,
	0x7b, 0x26, 0x55, 0x2c, 0x5c, 0xef, 0xdc, 0xf6, 0xaa, 0xc1, 0xbc, 0x3e, 0x05, 0xce, 0xa7, 0x06,
	0xae, 0x20, 0x1e, 0x34, 0xa9, 0xe2, 0x9f, 0x6b, 0x26, 0xb6, 0xb9, 0xd3, 0xa4, 0xb8, 0xa3, 0xac,
	0x85, 0x65, 0x98, 0x8f, 0x08, 0x71, 0xbf, 0x7f, 0x27, 0xa7, 0x4e, 0xb9, 0x7b, 0x23, 0x83, 0x7c,
	0x2f, 0xbb, 0x2d, 0xa9, 0x23, 0xa9, 0x1d, 0xdf, 0x38, 0x5d, 0xca, 0xff, 0x30, 0x5c, 0x43, 0x36,
	0xe5, 0xba, 0x72, 0x9e, 0x94, 0xcf, 0x11, 0xfb, 0x8e, 0x20, 0x9f, 0x6f, 0x87, 0x97, 0x90, 0xb4,
	0x87, 0x8e, 0x7a, 0xf3, 0xf8, 0x10, 0x74, 0x53, 0xb6, 0x4a, 0xff, 0xde, 0x52, 0xab, 0xc8, 0x8c,
	0xca, 0x39, 0xc3, 0x15, 0xa4, 0x9d, 0xd6, 0x83, 0xdf, 0xc9, 0x0b, 0x7f, 0x81, 0x9d, 0xee, 0x43,
	0x5d, 0x15, 0xb1, 0x9f, 0x3e, 0x66, 0x76, 0x0f, 0xb1, 0xbd, 0xde, 0x76, 0xec, 0xfd, 0xb3, 0x83,
	0xa7, 0x8c, 0x17, 0xf0, 0xdf, 0x88, 0x37, 0xea, 0x83, 0xda, 0x87, 0xe6, 0xc4, 0xfd, 0xc9, 0xbb,
	0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x10, 0x62, 0xac, 0xd9, 0x01, 0x00, 0x00,
}
