# Required only if using RBAC and Kubernetes Storage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: @dexRbacClusterRole@
rules:
- apiGroups: ["dex.coreos.com"] # API group created by dex
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: @dexRbacClusterRoleBinding@
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: @dexRbacClusterRole@
subjects:
- kind: ServiceAccount
  name: @dexServiceAccount@
  namespace: @namespace@
