apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: @ospreyApp@
  name: @ospreyDeployment@
  namespace: @namespace@
spec:
  replicas: 1
  selector:
    matchLabels:
      app: @ospreyApp@
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: @ospreyApp@
    spec:
      volumes:
        - name: ssl
          secret:
            secretName: @ospreySslSecret@

      containers:
        - name: osprey
          image: @ospreyImage@
          command:
            - /usr/local/bin/osprey
          args:
            - serve
            - cluster-info
            - --apiServerURL=@clusterApiServerURL@
            - --apiServerCA=/ssl/apiserver-ca.pem

          ports:
            - containerPort: @ospreyPort@
              name: osprey
              protocol: TCP

          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 150m
              memory: 256Mi

          volumeMounts:
            - mountPath: /ssl
              name: ssl
              readOnly: true
